spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

# 告知mybatis存放SQL文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志显示级别
logging:
  level:
    cn:
      tedu:
        csmall:
          sso: trace

