### 处理文件上传操作
POST http://localhost/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="picFile"; filename="a.jpg"

< d:/a.jpg
--WebAppBoundary--

### 删除磁盘中的文件
DELETE http://localhost/remove?name=0420d20f-b4d7-4dd8-a733-351d3228723b.jpg