### 登录
POST http://localhost/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 获取登录成功后的用户信息
GET http://localhost/user/currentUser

### 登出
GET http://localhost/user/logout