package cn.tedu.mapper;

import cn.tedu.pojo.Articles;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ArticlesMapper {
    int deleteByPrimaryKey(Long id);

    int insert(Articles record);

    Articles selectByPrimaryKey(Long id);

    List<Articles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_articles
     *
     * @mbggenerated Tue Jul 04 21:12:38 CST 2023
     */
    int updateByPrimaryKey(Articles record);

    List<Articles> selectByUserId(Long userId);
}